'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class GameDatabseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GameDatabseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tbl_actions() As DbSet(Of tbl_actions)
    Public Property tbl_game() As DbSet(Of tbl_game)
    Public Property tbl_player() As DbSet(Of tbl_player)
    Public Property tbl_player_actions() As DbSet(Of tbl_player_actions)
    Public Property tbl_player_game() As DbSet(Of tbl_player_game)

    Public Overridable Function intf_getCountPerAction(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of intf_getCountPerAction_Result)
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of intf_getCountPerAction_Result)("intf_getCountPerAction", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_getGameInfo(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of intf_getGameInfo_Result)
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of intf_getGameInfo_Result)("intf_getGameInfo", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_getPlayerGameMoveSelectionState(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of intf_getPlayerGameMoveSelectionState_Result)
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of intf_getPlayerGameMoveSelectionState_Result)("intf_getPlayerGameMoveSelectionState", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_getPlayerGameState(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of intf_getPlayerGameState_Result)
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of intf_getPlayerGameState_Result)("intf_getPlayerGameState", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_getPlayerInfo(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of tbl_player)
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player)("intf_getPlayerInfo", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_getPlayerInfo(prm_playerID As Nullable(Of Integer), mergeOption As MergeOption) As ObjectResult(Of tbl_player)
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player)("intf_getPlayerInfo", mergeOption, prm_playerIDParameter)
    End Function

    Public Overridable Function intf_getPlayerList() As ObjectResult(Of tbl_player)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player)("intf_getPlayerList")
    End Function

    Public Overridable Function intf_getPlayerList(mergeOption As MergeOption) As ObjectResult(Of tbl_player)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player)("intf_getPlayerList", mergeOption)
    End Function

    Public Overridable Function intf_getRunningGames() As ObjectResult(Of tbl_game)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_game)("intf_getRunningGames")
    End Function

    Public Overridable Function intf_getRunningGames(mergeOption As MergeOption) As ObjectResult(Of tbl_game)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_game)("intf_getRunningGames", mergeOption)
    End Function

    Public Overridable Function intf_initiateGame(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of intf_initiateGame_Result)
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of intf_initiateGame_Result)("intf_initiateGame", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_findPlayerAccount(prm_uName As String) As ObjectResult(Of Nullable(Of Integer))
        Dim prm_uNameParameter As ObjectParameter = If(prm_uName IsNot Nothing, New ObjectParameter("prm_uName", prm_uName), New ObjectParameter("prm_uName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("intf_findPlayerAccount", prm_uNameParameter)
    End Function

    Public Overridable Function intf_checkAccountLocked(prm_id As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_idParameter As ObjectParameter = If(prm_id.HasValue, New ObjectParameter("prm_id", prm_id), New ObjectParameter("prm_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_checkAccountLocked", prm_idParameter)
    End Function

    Public Overridable Function intf_comparePassword(prm_id As Nullable(Of Integer), prm_pWord As String) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_idParameter As ObjectParameter = If(prm_id.HasValue, New ObjectParameter("prm_id", prm_id), New ObjectParameter("prm_id", GetType(Integer)))

        Dim prm_pWordParameter As ObjectParameter = If(prm_pWord IsNot Nothing, New ObjectParameter("prm_pWord", prm_pWord), New ObjectParameter("prm_pWord", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_comparePassword", prm_idParameter, prm_pWordParameter)
    End Function

    Public Overridable Function intf_createPlayer(prm_uName As String, prm_pWord As String) As ObjectResult(Of Nullable(Of Integer))
        Dim prm_uNameParameter As ObjectParameter = If(prm_uName IsNot Nothing, New ObjectParameter("prm_uName", prm_uName), New ObjectParameter("prm_uName", GetType(String)))

        Dim prm_pWordParameter As ObjectParameter = If(prm_pWord IsNot Nothing, New ObjectParameter("prm_pWord", prm_pWord), New ObjectParameter("prm_pWord", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("intf_createPlayer", prm_uNameParameter, prm_pWordParameter)
    End Function

    Public Overridable Function intf_deletePlayer(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_deletePlayer", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_endGame(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_endGame", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_getGameState(prm_gameID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Byte))
        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Byte))("intf_getGameState", prm_gameIDParameter)
    End Function

    Public Overridable Function intf_isPlayerAdmin(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_isPlayerAdmin", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_newPlayerInstance(prm_playerID As Nullable(Of Integer), prm_gameID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Dim prm_gameIDParameter As ObjectParameter = If(prm_gameID.HasValue, New ObjectParameter("prm_gameID", prm_gameID), New ObjectParameter("prm_gameID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("intf_newPlayerInstance", prm_playerIDParameter, prm_gameIDParameter)
    End Function

    Public Overridable Function intf_playerActionRegister(prm_instID As Nullable(Of Integer), prm_action As Nullable(Of SByte)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_instIDParameter As ObjectParameter = If(prm_instID.HasValue, New ObjectParameter("prm_instID", prm_instID), New ObjectParameter("prm_instID", GetType(Integer)))

        Dim prm_actionParameter As ObjectParameter = If(prm_action.HasValue, New ObjectParameter("prm_action", prm_action), New ObjectParameter("prm_action", GetType(SByte)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_playerActionRegister", prm_instIDParameter, prm_actionParameter)
    End Function

    Public Overridable Function intf_playerDropout(prm_instanceID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_instanceIDParameter As ObjectParameter = If(prm_instanceID.HasValue, New ObjectParameter("prm_instanceID", prm_instanceID), New ObjectParameter("prm_instanceID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_playerDropout", prm_instanceIDParameter)
    End Function

    Public Overridable Function intf_playerLogin(prm_playerID As Nullable(Of Integer), prm_pWord As String) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Dim prm_pWordParameter As ObjectParameter = If(prm_pWord IsNot Nothing, New ObjectParameter("prm_pWord", prm_pWord), New ObjectParameter("prm_pWord", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_playerLogin", prm_playerIDParameter, prm_pWordParameter)
    End Function

    Public Overridable Function intf_playerLogout(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_playerLogout", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_updatePlayer(prm_playerID As Nullable(Of Integer), prm_uName As String, prm_pWord As String, prm_currentWinStreak As Nullable(Of Short), prm_highestWinStreak As Nullable(Of Short), prm_isLocked As Nullable(Of SByte), prm_isAdmin As Nullable(Of SByte)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Dim prm_uNameParameter As ObjectParameter = If(prm_uName IsNot Nothing, New ObjectParameter("prm_uName", prm_uName), New ObjectParameter("prm_uName", GetType(String)))

        Dim prm_pWordParameter As ObjectParameter = If(prm_pWord IsNot Nothing, New ObjectParameter("prm_pWord", prm_pWord), New ObjectParameter("prm_pWord", GetType(String)))

        Dim prm_currentWinStreakParameter As ObjectParameter = If(prm_currentWinStreak.HasValue, New ObjectParameter("prm_currentWinStreak", prm_currentWinStreak), New ObjectParameter("prm_currentWinStreak", GetType(Short)))

        Dim prm_highestWinStreakParameter As ObjectParameter = If(prm_highestWinStreak.HasValue, New ObjectParameter("prm_highestWinStreak", prm_highestWinStreak), New ObjectParameter("prm_highestWinStreak", GetType(Short)))

        Dim prm_isLockedParameter As ObjectParameter = If(prm_isLocked.HasValue, New ObjectParameter("prm_isLocked", prm_isLocked), New ObjectParameter("prm_isLocked", GetType(SByte)))

        Dim prm_isAdminParameter As ObjectParameter = If(prm_isAdmin.HasValue, New ObjectParameter("prm_isAdmin", prm_isAdmin), New ObjectParameter("prm_isAdmin", GetType(SByte)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_updatePlayer", prm_playerIDParameter, prm_uNameParameter, prm_pWordParameter, prm_currentWinStreakParameter, prm_highestWinStreakParameter, prm_isLockedParameter, prm_isAdminParameter)
    End Function

    Public Overridable Function intf_updatePlayerActivityTime(prm_playerID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_playerIDParameter As ObjectParameter = If(prm_playerID.HasValue, New ObjectParameter("prm_playerID", prm_playerID), New ObjectParameter("prm_playerID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_updatePlayerActivityTime", prm_playerIDParameter)
    End Function

    Public Overridable Function intf_checkAccountOnline(prm_id As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Boolean))
        Dim prm_idParameter As ObjectParameter = If(prm_id.HasValue, New ObjectParameter("prm_id", prm_id), New ObjectParameter("prm_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Boolean))("intf_checkAccountOnline", prm_idParameter)
    End Function

    Public Overridable Function intf_getInstanceInfo(prm_instanceID As Nullable(Of Integer)) As ObjectResult(Of tbl_player_game)
        Dim prm_instanceIDParameter As ObjectParameter = If(prm_instanceID.HasValue, New ObjectParameter("prm_instanceID", prm_instanceID), New ObjectParameter("prm_instanceID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player_game)("intf_getInstanceInfo", prm_instanceIDParameter)
    End Function

    Public Overridable Function intf_getInstanceInfo(prm_instanceID As Nullable(Of Integer), mergeOption As MergeOption) As ObjectResult(Of tbl_player_game)
        Dim prm_instanceIDParameter As ObjectParameter = If(prm_instanceID.HasValue, New ObjectParameter("prm_instanceID", prm_instanceID), New ObjectParameter("prm_instanceID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of tbl_player_game)("intf_getInstanceInfo", mergeOption, prm_instanceIDParameter)
    End Function

    Public Overridable Function intf_getInstanceSelection(prm_instanceID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Byte))
        Dim prm_instanceIDParameter As ObjectParameter = If(prm_instanceID.HasValue, New ObjectParameter("prm_instanceID", prm_instanceID), New ObjectParameter("prm_instanceID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Byte))("intf_getInstanceSelection", prm_instanceIDParameter)
    End Function

End Class
