'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_player_game
    Public Property id As Integer
    Public Property pID As Integer
    Public Property gID As Integer
    Public Property isHost As Boolean
    Public Property playerState As SByte
    Public Property joinTime As Date

End Class
