'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_game
    Public Property id As Integer
    Public Property gameState As SByte
    Public Property resetNumber As Integer
    Public Property roundNumber As Nullable(Of Short)
    Public Property stateStartTime As Date
    Public Property gameStartTime As Date
    Public Property gameEndTime As Nullable(Of Date)

End Class
